In [38]:
import csv 
import pandas as pd
import numpy as np

In [8]:
with open ('/home/AIML_Student/Documents/210962002/age.csv','r') as f:
    read=csv.reader(f)
    for row in read:
        print(row)


['S.NO', 'name ', 'age']
['1', 'sid', '20']
['2', 'ronan', '19']
['3', 'abhiram', '21']
['4', 'shreyas', '24']
['5', 'aman', '23']


In [12]:
reader=pd.read_csv('/home/AIML_Student/Documents/210962002/age.csv')
print(reader)

   S.NO    name   age
0     1      sid   20
1     2    ronan   19
2     3  abhiram   21
3     4  shreyas   24
4     5     aman   23


In [15]:
with open ('/home/AIML_Student/Documents/210962002/AGE1.csv','r') as f:
    read=csv.reader(f)
    for row in read:
        print(row)


['sno', 'name', 'age']
['1', 'SID', '20']
['2', 'SHREYAS', '19']
['3', 'ABHIRAM', '25']
['4', 'AMAN', '21']
['5', 'RONAN', '28']


In [19]:
textRead=pd.read_csv('/home/AIML_Student/Documents/210962002/AGE1.csv')
print(textRead)

   sno     name  age
0    1      SID   20
1    2  SHREYAS   19
2    3  ABHIRAM   25
3    4     AMAN   21
4    5    RONAN   28


In [21]:
with open ('/home/AIML_Student/Documents/210962002/AGE1.csv','r') as f:
    read=csv.DictReader(f)
    for row in read:
        print(row)


{'sno': '1', 'name': 'SID', 'age': '20'}
{'sno': '2', 'name': 'SHREYAS', 'age': '19'}
{'sno': '3', 'name': 'ABHIRAM', 'age': '25'}
{'sno': '4', 'name': 'AMAN', 'age': '21'}
{'sno': '5', 'name': 'RONAN', 'age': '28'}


In [23]:
with open ('/home/AIML_Student/Documents/210962002/write.csv','w') as file:
    write=csv.writer(file,delimiter=',')
    write.writerow(['programing Langyuage','designed by','appeaered','Extension'])
    write.writerow(['Python','Guido van russo','1991','.py'])
    write.writerow(['java','james gosling','1995','.java'])
    write.writerow(['C++','Bjarne','1985','.cpp'])
    

In [26]:
from pandas import DataFrame
c={'programing Langyuage':['Python','java','C++'],
   'designed by':['Guido van russo','james gosling','Bjarne'],
   'appeaered':['1991','1995','1985'],
   'Extension':['.py','.java','.cpp']}
df=DataFrame(c,columns=['programing Langyuage','designed by','appeaered','Extension'])
export_csv=df.to_csv(r'/home/AIML_Student/Documents/210962002/data1.csv',index=None)
print(df)

  programing Langyuage      designed by appeaered Extension
0               Python  Guido van russo      1991       .py
1                 java    james gosling      1995     .java
2                  C++           Bjarne      1985      .cpp


In [34]:
import scipy
import matplotlib
import seaborn
import sklearn
#___

In [40]:
a=np.array([1,2,3,4,5,6,7,8,9])
r=a.reshape(3,3)
print(r)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
for i in range(len(a)):
    if a[i]%2!=0:
        a[i]=-1
    if a[i]==1:
        a[i]=-1
        
        
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [55]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
g=np.where(x>y)
e=np.where(x==y)
print("greater x than y",g)
print("equal x and y",e)


greater x than y (array([1, 2, 4, 5, 6, 7, 8, 9]),)
equal x and y (array([0]),)


In [64]:
q=np.arange(100).reshape(5,-1)
print(q[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
